
import java.util.HashSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pixie
 */
public class LoginAdmin extends javax.swing.JFrame {

    /**
     * Creates new form LoginAdmin
     */
    
    IngresoAlumno alum = null;
    Curso curso=null;
    MantenedorDestinos destino=null;
    MantenedorCuenta cuenta = null;
    MantenedorActividad actividad = null;
    MantenedorRegiones region = null;
    MantenedorEscuela escuela = null;
    CtaRol rol =null;
    Servicios servicio = null;
    public LoginAdmin() {
        initComponents();
        alum = new IngresoAlumno();
        curso = new Curso();
        destino = new MantenedorDestinos();
        cuenta = new MantenedorCuenta();
        actividad = new MantenedorActividad();
        region = new MantenedorRegiones();
        escuela = new MantenedorEscuela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Alumno = new javax.swing.JButton();
        btn_Curso = new javax.swing.JButton();
        btn_Destinos = new javax.swing.JButton();
        btn_Cta = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Region = new javax.swing.JButton();
        btn_Escuela = new javax.swing.JButton();
        btn_CtaRol = new javax.swing.JButton();
        btn_servicios = new javax.swing.JButton();
        btn_Actividad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bievenido/a Administrador");

        btn_Alumno.setText("Mantendor ALumno");
        btn_Alumno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlumnoActionPerformed(evt);
            }
        });

        btn_Curso.setText("Mantenedor Curso");
        btn_Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CursoActionPerformed(evt);
            }
        });

        btn_Destinos.setText("Mantendor Destinos");
        btn_Destinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DestinosActionPerformed(evt);
            }
        });

        btn_Cta.setText("Mantenedor Cuenta");
        btn_Cta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CtaActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Salir");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        btn_Region.setText("Agregar región");
        btn_Region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegionActionPerformed(evt);
            }
        });

        btn_Escuela.setText("Agregar Escuela");
        btn_Escuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EscuelaActionPerformed(evt);
            }
        });

        btn_CtaRol.setText("Agregar Cuenta Rol");
        btn_CtaRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CtaRolActionPerformed(evt);
            }
        });

        btn_servicios.setText("Agregar Servicios");
        btn_servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_serviciosActionPerformed(evt);
            }
        });

        btn_Actividad.setText("Mantenedor Actividad");
        btn_Actividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_Curso)
                        .addComponent(btn_Alumno)
                        .addComponent(btn_Destinos)
                        .addComponent(btn_Cta)
                        .addComponent(btn_Actividad)))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Region)
                    .addComponent(btn_Escuela)
                    .addComponent(btn_CtaRol)
                    .addComponent(btn_servicios))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Cancelar)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Alumno)
                    .addComponent(btn_Region))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Curso)
                    .addComponent(btn_Escuela))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Destinos)
                    .addComponent(btn_CtaRol))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cta)
                    .addComponent(btn_servicios))
                .addGap(18, 18, 18)
                .addComponent(btn_Actividad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Cancelar)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlumnoActionPerformed
        // TODO add your handling code here:
        IngresoAlumno second = new IngresoAlumno();
        
        this.setVisible(false);
        alum.setVisible(true);
        
        //this.dispose();
        
    }//GEN-LAST:event_btn_AlumnoActionPerformed

    private void btn_EscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EscuelaActionPerformed
        // TODO add your handling code here:
        MantenedorEscuela second = new MantenedorEscuela();
      
        this.setVisible(false);
        escuela.setVisible(true);

        
        //this.dispose();
        
    }//GEN-LAST:event_btn_EscuelaActionPerformed

    private void btn_CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CursoActionPerformed
        // TODO add your handling code here:
        Curso second = new Curso();
        
        this.setVisible(false);
        curso.setVisible(true);
        
    }//GEN-LAST:event_btn_CursoActionPerformed

    private void btn_serviciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_serviciosActionPerformed
        // TODO add your handling code here:
        Servicios second = new Servicios();
       
        this.setVisible(false);
        servicio.setVisible(true);
        
    }//GEN-LAST:event_btn_serviciosActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_DestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DestinosActionPerformed
        // TODO add your handling code here:
        MantenedorDestinos second = new MantenedorDestinos();
       
        this.setVisible(false);
        destino.setVisible(true);
        
        
    }//GEN-LAST:event_btn_DestinosActionPerformed

    private void btn_CtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CtaActionPerformed
        // TODO add your handling code here:
        MantenedorCuenta second = new MantenedorCuenta();
        
        this.setVisible(false);
        cuenta.setVisible(true);
        
        
    }//GEN-LAST:event_btn_CtaActionPerformed

    private void btn_ActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActividadActionPerformed
        // TODO add your handling code here:
        MantenedorActividad second = new MantenedorActividad();
       
        this.setVisible(false); 
        actividad.setVisible(true);
        
        
        
    }//GEN-LAST:event_btn_ActividadActionPerformed

    private void btn_RegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegionActionPerformed
        // TODO add your handling code here:
        MantenedorRegiones second = new MantenedorRegiones();
     
        this.setVisible(false);
        region.setVisible(true);
        
        
    }//GEN-LAST:event_btn_RegionActionPerformed

    private void btn_CtaRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CtaRolActionPerformed
        // TODO add your handling code here:
        CtaRol second = new CtaRol();
        
        this.setVisible(false);
        rol.setVisible(true);
        
    }//GEN-LAST:event_btn_CtaRolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actividad;
    private javax.swing.JButton btn_Alumno;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Cta;
    private javax.swing.JButton btn_CtaRol;
    private javax.swing.JButton btn_Curso;
    private javax.swing.JButton btn_Destinos;
    private javax.swing.JButton btn_Escuela;
    private javax.swing.JButton btn_Region;
    private javax.swing.JButton btn_servicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
